[package]
name = "poker"
version = "0.1.0"
authors = ["Sach97 <sacha.arbonel@hotmail.fr>"]
edition = "2018"

[dependencies]


[lib]
name = "poker"
path = "src/lib.rs"

[[bin]]
name = "poker"
path = "src/bin.rs"